name: ci

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: juancamiloclement
          password: clement25-98

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: juancamiloclement/dockerapp-js:latest